rendering.ipynb: fix style used for Thredds v5
For the following error:
```
  _______ pavics-sdi-master/docs/source/notebooks/rendering.ipynb::Cell 2 ________
  Notebook cell execution failed
  Cell 2: Cell outputs differ

  Input:
  sorted(wms.contents["tasmax"].styles.keys())

  Traceback:
   mismatch 'text/plain'

   assert reference_output == test_output failed:

    "['boxfill/al...fill/sst_36']" == "['colored_co...ter/default']"

    - ['colored_contours/default',
    -  'contours',
    -  'default-scalar/default',
    -  'raster/default']
    + ['boxfill/alg',
    +  'boxfill/alg2',
    +  'boxfill/ferret',
    +  'boxfill/greyscale',
    +  'boxfill/ncview',
    +  'boxfill/occam',
    +  'boxfill/occam_pastel-30',
    +  'boxfill/rainbow',
    +  'boxfill/redblue',
    +  'boxfill/sst_36']

  _______ pavics-sdi-master/docs/source/notebooks/rendering.ipynb::Cell 3 ________
  Notebook cell execution failed
  Cell 3: Cell execution caused an exception

  Input:
  resp = wms.getmap(
      layers=["tasmax"],
      styles=["boxfill/occam"],
      format="image/png",
      colorscalerange=f"{mn},{mx}",
      size=[256, 256],
      srs="CRS:84",
      bbox=(150, 30, 250, 80),
      time="2006-02-15",
      transparent=True,
  )
  Image(resp.read())

  Traceback:

  ---------------------------------------------------------------------------
  ServiceException                          Traceback (most recent call last)
  Cell In[1], line 1
  ----> 1 resp = wms.getmap(
        2     layers=["tasmax"],
        3     styles=["boxfill/occam"],
        4     format="image/png",
        5     colorscalerange=f"{mn},{mx}",
        6     size=[256, 256],
        7     srs="CRS:84",
        8     bbox=(150, 30, 250, 80),
        9     time="2006-02-15",
       10     transparent=True,
       11 )
       12 Image(resp.read())

  File /opt/conda/envs/birdy/lib/python3.11/site-packages/owslib/map/wms130.py:309, in WebMapService_1_3_0.getmap(self, layers, styles, srs, bbox, format, size, time, elevation, dimensions, transparent, bgcolor, exceptions, method, timeout, **kwargs)
      305 data = urlencode(request)
      307 self.request = bind_url(base_url) + data
  --> 309 u = openURL(base_url, data, method, timeout=timeout or self.timeout, auth=self.auth, headers=self.headers)
      311 # need to handle casing in the header keys
      312 headers = {}

  File /opt/conda/envs/birdy/lib/python3.11/site-packages/owslib/util.py:210, in openURL(url_base, data, method, cookies, username, password, timeout, headers, verify, cert, auth)
      207 req = requests.request(method.upper(), url_base, headers=headers, **rkwargs)
      209 if req.status_code in [400, 401]:
  --> 210     raise ServiceException(req.text)
      212 if req.status_code in [404, 500, 502, 503, 504]:    # add more if needed
      213     req.raise_for_status()

  ServiceException: <ServiceExceptionReport version="1.3.0"
                          xmlns="http://www.opengis.net/ogc"
                          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                          xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
      <ServiceException code="StyleNotDefined">
          The layer tasmax does not support the style boxfill
      </ServiceException>
  </ServiceExceptionReport>
```