subset-user-input.ipynb: fix for Jenkins to run against test servers
Any NCML catalogs have to come from the production server since that's
too much data to replicate to all the various test servers.

So the catalog string have to hardcode "pavics.ouranos.ca" and use the
marker TEST_USE_PROD_DATA, all on the same line.

Fix this kind of error:
```
OSError: [Errno -70] NetCDF: DAP server error: b'https://medus.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/datasets/gridded_obs/nrcan_v2.ncml'
```