subsetting.ipynb: fix Jenkins failure since FP upgrade from 1.5.1 to 1.6
Code changed to account for new metalink and removed tar archive.

Failure with new Jupyter image:

```
17:03:43  _______ pavics-sdi-master/docs/source/notebooks/subsetting.ipynb::Cell 2 _______
17:03:43  Notebook cell execution failed
17:03:43  Cell 2: Cell outputs differ
17:03:43
17:03:43  Input:
17:03:43  help(fp.subset_continents)
17:03:43
17:03:43  Traceback:
17:03:43   mismatch 'stdout'
17:03:43
17:03:43   assert reference_output == test_output failed:
17:03:43
17:03:43    'Help on meth... dataset.\n\n' == 'Help on meth... outputs.\n\n'
17:03:43    Skipping 101 identical leading characters in diff, use -v to show
17:03:43    - n='Africa') method of birdy.client.base.WPSClient instance
17:03:43    + n='Africa', mosaic=False) method of birdy.client.base.WPSClient instance
17:03:43    ?           ++++++++++++++
17:03:43          Return the data whose grid cells intersect the selected continents for each input dataset.
17:03:43
17:03:43          Parameters
17:03:43          ----------
17:03:43          region : {'Africa', 'Asia', 'Australia', 'North America', 'Oceania', 'South America', 'Antarctica', 'Europe'}string
17:03:43              Continent name.
17:03:43    +     mosaic : boolean
17:03:43    +         If True, selected regions will be merged into a single geometry.
17:03:43          resource : ComplexData:mimetype:`application/x-netcdf`, :mimetype:`application/x-tar`, :mimetype:`application/zip`
17:03:43              NetCDF Files or archive (tar/zip) containing netCDF files.
17:03:43
17:03:43          Returns
17:03:43          -------
17:03:43    +     output : ComplexData:mimetype:`application/x-tar`
17:03:43    +         Tar archive of the subsetted netCDF files.
17:03:43    -     output : ComplexData:mimetype:`application/x-netcdf`
17:03:43    ?        ---
17:03:43    +     ncout : ComplexData:mimetype:`application/x-netcdf`
17:03:43    ?     ++
17:03:43    +         NetCDF file with subset for one dataset.
17:03:43    -         NetCDF output for first resource file.
17:03:43    -     metalink : ComplexData:mimetype:`application/metalink+xml; version=4.0`
17:03:43    -         Metalink file with links to all NetCDF outputs.
17:03:43
17:03:43
17:03:43
17:03:43  _______ pavics-sdi-master/docs/source/notebooks/subsetting.ipynb::Cell 4 _______
17:03:43  Notebook cell execution failed
17:03:43  Cell 4: Cell outputs differ
17:03:43
17:03:43  Input:
17:03:43  tar_url, nc_out_url = resp.get()
17:03:43  print("URL: ", nc_out_url)
17:03:43  tar_out, nc_out = resp.get(asobj=True)
17:03:43  nc_out
17:03:43
17:03:43  Traceback:
17:03:43  Missing output fields from running code: {'text/html'}
```

Failure with old Jupyter image:

```
20:35:36  pavics-sdi-master/docs/source/notebooks/subsetting.ipynb ..
20:35:36  INTERNALERROR> Traceback (most recent call last):
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/main.py", line 191, in wrap_session
20:35:36  INTERNALERROR>     session.exitstatus = doit(config, session) or 0
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/main.py", line 247, in _main
20:35:36  INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
20:35:36  INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
20:35:36  INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
20:35:36  INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
20:35:36  INTERNALERROR>     return outcome.get_result()
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
20:35:36  INTERNALERROR>     raise ex[1].with_traceback(ex[2])
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
20:35:36  INTERNALERROR>     res = hook_impl.function(*args)
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/main.py", line 272, in pytest_runtestloop
20:35:36  INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
20:35:36  INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
20:35:36  INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
20:35:36  INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
20:35:36  INTERNALERROR>     return outcome.get_result()
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
20:35:36  INTERNALERROR>     raise ex[1].with_traceback(ex[2])
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
20:35:36  INTERNALERROR>     res = hook_impl.function(*args)
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/runner.py", line 85, in pytest_runtest_protocol
20:35:36  INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/runner.py", line 100, in runtestprotocol
20:35:36  INTERNALERROR>     reports.append(call_and_report(item, "call", log))
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/_pytest/runner.py", line 188, in call_and_report
20:35:36  INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
20:35:36  INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
20:35:36  INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
20:35:36  INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
20:35:36  INTERNALERROR>     gen.send(outcome)
20:35:36  INTERNALERROR>   File "/opt/conda/envs/birdy/lib/python3.7/site-packages/dash/testing/plugin.py", line 79, in pytest_runtest_makereport
20:35:36  INTERNALERROR>     for name, fixture in item.funcargs.items():
20:35:36  INTERNALERROR> AttributeError: 'IPyNbCell' object has no attribute 'funcargs'
```