subset-user-input.ipynb: catalog url changed
Fix this error:

```
  ___ pavics-sdi-master/docs/source/notebooks/subset-user-input.ipynb::Cell 12 ___
  Notebook cell execution failed
  Cell 12: Cell execution caused an exception

  Input:
  # gather data from the PAVICS data catalogue
  catalog = "https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/catalog/datasets/gridded_obs/catalog.xml"  # TEST_USE_PROD_DATA

  cat = TDSCatalog(catalog)
  data = [
      cat.datasets[d].access_urls["OPENDAP"] for d in cat.datasets if "nrcan_v2" in d
  ][0]
  data

  Traceback:

  ---------------------------------------------------------------------------
  IndexError                                Traceback (most recent call last)
  Cell In[1], line 5
        1 # gather data from the PAVICS data catalogue
        2 catalog = "https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/catalog/datasets/gridded_obs/catalog.xml"  # TEST_USE_PROD_DATA
        3
        4 cat = TDSCatalog(catalog)
  ----> 5 data = [
        6     cat.datasets[d].access_urls["OPENDAP"] for d in cat.datasets if "nrcan_v2" in d
        7 ][0]
        8 data

  IndexError: list index out of range
```