climate_indices.ipynb: birdy.client.outputs.WPSResult.get() do not have arg verify
Not sure why I added verify to get().  Probably a blind fix since flyingpigeon
was always failing and I was not able to test for real so had to do a blind
fix.

thredds = 'https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/fileServer/birdhouse/testdata/flyingpigeon/'
resp = fp.icclim_tx(resource=thredds+'cmip3/tas.sresb1.giss_model_e_r.run1.atm.da.nc', grouping='yr')
tx, log = resp.get(asobj=True, verify=verify_ssl)
tx

Traceback:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-2c6df49c79c5> in <module>
      1 thredds = 'https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/fileServer/birdhouse/testdata/flyingpigeon/'
      2 resp = fp.icclim_tx(resource=thredds+'cmip3/tas.sresb1.giss_model_e_r.run1.atm.da.nc', grouping='yr')
----> 3 tx, log = resp.get(asobj=True, verify=verify_ssl)
      4 tx

TypeError: get() got an unexpected keyword argument 'verify'

Help on WPSExecution in module birdy.client.utils object:

class WPSExecution(birdy.client.outputs.WPSResult, owslib.wps.WPSExecution)
 |  Class that represents a single WPS process executed on a remote WPS service.
 |
 |  Method resolution order:
 |      WPSExecution
 |      birdy.client.outputs.WPSResult
 |      owslib.wps.WPSExecution
 |      builtins.object
 |
 |  Methods inherited from birdy.client.outputs.WPSResult:
 |
 |  attach(self, wps_outputs, converters=None)
 |      Args:
 |          converters (dict): Converter dictionary {name: object}
 |
 |  get(self, asobj=False)
 |      Args:
 |          asobj: If True, object_converters will be used.